on: push
name: Compile
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        branch: [master]
        python: [3.7]
        os: [ubuntu-latest]
        # branch: [r2.1, r2.2, r2.3]  # r2.1,
        # python: [3.5, 3.6, 3.7, 3.8] #
        # os: [macos-latest, ubuntu-latest]  #
        version_suffix: [.testtestest]

    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Clone
      run: |
        git clone https://github.com/tensorflow/tensorflow.git ../tensorflow
        git -C ../tensorflow checkout ${{ matrix.branch }}

    - name: Platform Installs | Linux
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get install swig libjpeg-dev zlib1g-dev -y

    - name: Platform Installs | Mac
      if: startsWith(matrix.os, 'macos')
      run: brew install swig libjpeg

    - name: Installs
      run: pip install numpy pybind11 wheel


    - name: Build
      run: |
        /bin/bash ../tensorflow/tensorflow/lite/tools/make/download_dependencies.sh
        /bin/bash ../tensorflow/tensorflow/lite/tools/pip_package/build_pip_package.sh
      env:
        VERSION_SUFFIX: ${{ matrix.version_suffix }}

    - uses: actions/checkout@master

    - name: copy over wheels
      run: |
        pwd
        ls -lah
        FILES=$(find /tmp/tflite_pip ../tensorflow/tensorflow/lite -name "tflite_runtime*.whl" 2>/dev/null || :)
        echo 55555 $FILES
        mkdir -p dist
        for f in $FILES; do
          f2=dist/$(basename "$f" | sed -e 's/linux/manylinux2014/g')
          echo $f $f2
          mv "$f" "$f2"
        done
        ls -lah
        ls -lah dist/

    # push github
    - name: commit files
      run: |
        git config --global user.email "bea.steers@gmail.com"
        git config --global user.name "Bea Steers"
        git add dist/
        git commit -m 'adding whl for ${{ matrix.os }}:${{ matrix.python }}'

        n=0
        until [ "$n" -ge 12 ]; do
           git pull && git push && break
           n=$((n+1))
           sleep $((1 + $RANDOM % 4))
        done

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Publish package to TestPyPI
    #   uses: pypa/gh-action-pypi-publish@master
    #   with:
    #     user: ${{ secrets.pypi_user }}
    #     password: ${{ secrets.pypi_password }}
    #     repository_url: https://test.pypi.org/simple
    #     skip_existing: true
