on: push
name: Compile
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        branch: [master]  # r2.1,
        python: [3.5, 3.6, 3.7, 3.8]
        os: [macos-latest, ubuntu-latest]  # , windows-latest

    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Clone
      run: |
        git clone https://github.com/tensorflow/tensorflow.git
        git -C tensorflow checkout ${{ matrix.branch }}

    - name: Platform Installs | Linux
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get install swig libjpeg-dev zlib1g-dev -y

    - name: Platform Installs | Mac
      if: startsWith(matrix.os, 'macos')
      run: |
        brew install swig libjpeg

    # - name: Platform Installs | Mac
    #   run: |
    #     brew install swig libjpeg

    - name: Installs
      run: |
        pip install numpy pybind11 wheel
    - name: Build
      run: |
        /bin/bash tensorflow/tensorflow/lite/tools/make/download_dependencies.sh
        /bin/bash tensorflow/tensorflow/lite/tools/pip_package/build_pip_package.sh
    - name: ls
      run: |
        pwd
        ls
    # - name: change linux to manylinux2014
    #   run: |
    #     for f in dist/*; do
    #       f2=$(sed -i -e 's/linux/manylinux2014/g' "$f")
    #       echo $f $f2
    #       mv "$f" "$f2"
    #     done
    - name: commit files
      run: |
        git add dist/*
        git commit -m 'adding whl for ${{ matrix.os }}:${{ matrix.python }}'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Publish package to TestPyPI
    #   uses: pypa/gh-action-pypi-publish@master
    #   with:
    #     user: ${{ secrets.pypi_user }}
    #     password: ${{ secrets.pypi_password }}
    #     repository_url: https://test.pypi.org/simple
    #     skip_existing: true
